version: "3"
services:

  prod_mysql_container:
    container_name: prod_mysql_container
    image: mysql:8.0
    ports:
      - ${PROD_MYSQL_BINDING_PORT}:3306
    volumes:
      - ${PROD_MYSQL_DATA_PATH}:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: unless-stopped

  prod_redis_container:
    container_name: prod_redis_container
    image: redis:6.2.6-alpine
    ports:
      - ${PROD_REDIS_BINDING_PORT}:6379
    restart: unless-stopped

  prod_spring_container:
    container_name: prod_spring_container
    image: docker-prod
    ports:
      - ${PROD_SPRING_BINDING_PORT}:8080
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - prod_mysql_container
      - prod_redis_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://j10a309.p.ssafy.io:${PROD_MYSQL_BINDING_PORT}/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_ROOT_HOST}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
      EXCHANGE_RATE_API_KEY: ${EXCHANGE_RATE_API_KEY}
    restart: always
